name: Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: xcodebuild
    - run: ls -la build/Release
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
